require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/appointments", type: :request do
  let!(:appointment) { create(:appointment) }
  let(:valid_attributes) {{ date: "01/01/2099", time: "12", doctor_id: appointment.doctor.id }}
  let(:invalid_attributes) {{ date: "021/01/209", time: "36", doctor_id: appointment.doctor.id }}

  describe "GET /index" do
    it "renders a successful response" do
      get appointments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get appointment_url(appointment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_appointment_url(doctor_id: appointment.doctor.id)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Appointment" do
        expect {
          post appointments_url, params: { appointment: valid_attributes }
        }.to change(Appointment, :count).by(1)
      end

      it "redirects to the client form" do
        post appointments_url, params: { appointment: valid_attributes }
        expect(response).to redirect_to(new_client_path)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Appointment" do
        expect {
          post appointments_url, params: { appointment: invalid_attributes }
        }.to change(Appointment, :count).by(0)
      end

      it "redirects back to the appointments form with errors" do
        post appointments_url, params: { appointment: invalid_attributes }

        expect(response).to redirect_to(new_appointment_path)
        expect(flash[:notice]).to be_present
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested appointment" do
      expect {
        delete appointment_url(appointment)
      }.to change(Appointment, :count).by(-1)
    end

    it "redirects to the appointments list" do
      delete appointment_url(appointment)
      expect(response).to redirect_to(appointments_url)
    end
  end

  describe "POST /list" do
    context "with valid parameters" do
      it "redirects to the my_appointments page" do
        post list_appointment_path, params: { email: appointment.client.email }
        expect(response).to redirect_to(client_path(id: appointment.client.id))
      end
    end

    context "with invalid parameters" do
      it "redirects back to the email form with errors" do
        post list_appointment_path, params: { email: nil }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "GET /download" do
    context "if the file type is supported" do
      it 'sends the file as an attachment' do
        get download_appointment_path(id: appointment.id, format: "csv")

        expect(response.headers["Content-Disposition"]).to include("attachment")
        expect(response.headers["Content-Type"]).to eq("text/csv")
        expect(response).to have_http_status(:success)
      end
    end
  end
end
